# =========================
# HAT x2 from scratch (DF2K) + ESC(HAB) + CSA+Memory (OCAB 대체)
# =========================

# --- general settings ---
name: train_HAT_SRx2_ESC_OCAB_from_scratch
model_type: HATModel
scale: 2
num_gpu: auto
manual_seed: 0

# --- datasets & loaders ---
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/DF2K_HR_sub
    dataroot_lq: datasets/DF2K/DF2K_LR_bicubic/X2_sub
    meta_info_file: hat/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend: { type: disk }

    gt_size: 128
    use_hflip: true
    use_rot: true

    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set5/GTmod2
    dataroot_lq: ./datasets/Set5/LRbicx2
    io_backend: { type: disk }

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set14/GTmod2
    dataroot_lq: ./datasets/Set14/LRbicx2
    io_backend: { type: disk }

# --- network (HATX: Dual-Branch) ---
network_g:
  type: HATX
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.0

  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: pixelshuffle
  resi_connection: '1conv'

  # --- Local branch: ESC (HAB) ---
  esc_pdim: 16
  esc_kernel: 13

  # --- Global branch: Cross-Scale Attention + Memory ---
  csa_heads: 6
  csa_down_ratio: 2
  csa_mem_size: 16

  # --- FFT-gated ---
  fft_bands: 3
  fft_res_scale: 0.15

  # --- Iterative refinement ---
  iterative_T: 1

# --- paths ---
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# --- training ---
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warmup

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# --- validation ---
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: false
  tile: 64
  tile_pad: 16
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher

# --- logging ---
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# --- distributed ---
dist_params:
  backend: nccl
  port: 29500
