# =========================
# HATX x2 from scratch (DF2K) + ESC(HAB) + OCAB(ESC on)
# PSNR-oriented config (no GAN/perc)
# =========================

# --- general settings ---
name: train_HATX_SRx2_ESC_OCAB_PSNR
model_type: HATModel
scale: 2
num_gpu: auto
manual_seed: 0

# --- datasets & loaders ---
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/DF2K_HR_sub
    dataroot_lq: datasets/DF2K/DF2K_LR_bicubic/X2_sub
    meta_info_file: hat/data/meta_info/meta_info_DF2Ksub_GT.txt
    io_backend: { type: disk }

    gt_size: 128
    use_hflip: true
    use_rot: true

    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set5/GTmod2
    dataroot_lq: ./datasets/Set5/LRbicx2
    io_backend: { type: disk }

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set14/GTmod2
    dataroot_lq: ./datasets/Set14/LRbicx2
    io_backend: { type: disk }

# --- network (HATX: PSNR-tuned) ---
network_g:
  type: HATX
  upscale: 2
  in_chans: 3
  img_size: 64
  window_size: 16          # 메모리 여유되면 16 유지, 부족하면 8/12로 조절
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.03         # ↑ 0.01 -> 0.03 (권장 스윗스팟 0.02~0.03)
  overlap_ratio: 0.6       # ↑ 0.5 -> 0.6 (경계 안정화)
  img_range: 1.0

  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]

  # 비고: HATX에서는 HAB FFN 비율(SGFN)과 OCAB MLP 비율을 분리
  hab_ffn_ratio: 3.0       # HAB 전용 FFN (Spatial-Gate DConv FFN) 비율
  mlp_ratio: 4.0           # OCAB MLP는 4.0 권장
  upsampler: pixelshuffle
  resi_connection: '1conv'

  # --- HAB (Local ESC) ---
  esc_pdim: 24             # ↑ 16 -> 24
  esc_kernel: 15           # ↑ 13 -> 15

  # --- OCAB (ESC 주입 활성) ---
  ocab_esc_enable: true
  ocab_esc_pdim: 32        # ↑ 16 -> 32
  ocab_esc_kernel: 17      # ↑ 13 -> 17

  # --- 집중 어텐션 옵션 ---
  kv_topk_ratio: 0.6       # < 1.0이면 Top-K 프루닝 활성 (0.5~0.8 권장)
  use_focus_bias: true     # Focus bias 헤드 활성 (로짓 가산)

# --- paths ---
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# --- training ---
train:
  ema_decay: 0.9995        # ↑ 0.999 -> 0.9995 (EMA로 검증/저장 안정화)

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warmup

  # losses (PSNR 지향)
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# --- validation ---
val:
  val_freq: !!float 5e3
  save_img: true
  pbar: false
  tile: 64
  tile_pad: 16
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher

# --- logging ---
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# --- distributed ---
dist_params:
  backend: nccl
  port: 29500
